#!/bin/bash

python=`command -v pip3`

#dependencies
if ! [ $python ]; then
    echo -e "installing python3 & pip3"
    sudo eopkg install python3 &> /dev/null
fi

if ! [ exiftool ]; then
    echo -e "installing exiftool"
    sudo eopkg install perl-image-exiftool
fi

if ! [ eyeD3 ]; then
	echo -e "installing eyeD3"
	pip3 install eyeD3
fi

#move the startups
sudo cp rbtopopm /usr/local/bin/
sudo cp popmtorb /usr/local/bin/
sudo chmod +x /usr/local/bin/rbtopopm
sudo chmod +x /usr/local/bin/popmtorb
#compile the jars
javac RBToPOPM.java POPMToRB.java ID3Reader.java Rating.java
jar cvf RhythmBoxToPOPM.jar RBToPOPM.class
jar cvf POPMToRhythmBox.jar POPMToRB.class ID3Reader.class Rating.class
#move the jars
sudo cp RhythmBoxToPOPM.jar /usr/local/bin/
sudo cp POPMToRhythmBox.jar /usr/local/bin/
