#!/bin/bash
#vars
python=`command -v pip3`

#generic
msg_installing() {
	echo -e "🚧 installing $1\n"
}

msg_installed() {
	echo -e "✅ $1 already installed\n"
}

#dependencies
if ! [ $python ]; then
    msg_installing "python3 & pip3"
    sudo eopkg install python3 &> /dev/null
else
	msg_installed "python3 & pip"
fi

if ! [ exiftool ]; then
    msg_installing "exiftool"
    sudo eopkg install perl-image-exiftool &> /dev/null
else
	msg_installed "exiftool"
fi

if ! [ eyeD3 ]; then
	msg_installing "eyeD3"
	pip3 install eyeD3 &> /dev/null
else
	msg_installed "eyeD3"
fi

#move the startups
sudo cp rbtopopm /usr/local/bin/
sudo cp popmtorb /usr/local/bin/
sudo chmod +x /usr/local/bin/rbtopopm
sudo chmod +x /usr/local/bin/popmtorb
#compile the jars
javac RBToPOPM.java POPMToRB.java ID3Reader.java Rating.java
jar cvf RhythmBoxToPOPM.jar RBToPOPM.class
jar cvf POPMToRhythmBox.jar POPMToRB.class ID3Reader.class Rating.class
#move the jars
sudo cp RhythmBoxToPOPM.jar /usr/local/bin/
sudo cp POPMToRhythmBox.jar /usr/local/bin/
