#!/bin/bash
#vars
python=`command -v pip3`

#generic
msg_installing() {
	echo -e "🚧 installing $1\n"
}

msg_installed() {
	echo -e "✅ $1 already installed\n"
}

#dependencies
if ! [ $python ]; then
    msg_installing "python3 & pip3"
    sudo eopkg install python3 &> /dev/null
else
	msg_installed "python3 & pip"
fi

if ! [ exiftool ]; then
    msg_installing "exiftool"
    sudo eopkg install perl-image-exiftool &> /dev/null
else
	msg_installed "exiftool"
fi

if ! [ eyeD3 ]; then
	msg_installing "eyeD3"
	pip3 install eyeD3 &> /dev/null
else
	msg_installed "eyeD3"
fi

#move the startups
echo -e "🗑️  sending 'rbtopopm' to /usr/bin\n"
sudo cp rbtopopm /usr/bin/
sudo chmod +x /usr/bin/rbtopopm

echo -e "🗑️  sending 'popmtorb' to /usr/bin\n"
sudo cp popmtorb /usr/bin
sudo chmod +x /usr/bin/popmtorb

#compile the jars
echo -e "☕ compiling and sending the jars to /usr/bin\n"
javac RBToPOPM.java POPMToRB.java ID3Reader.java Rating.java &> /dev/null
jar cvf RhythmBoxToPOPM.jar RBToPOPM.class &> /dev/null
jar cvf POPMToRhythmBox.jar POPMToRB.class ID3Reader.class Rating.class &> /dev/null
#move the jars
sudo cp RhythmBoxToPOPM.jar /usr/bin/
sudo cp POPMToRhythmBox.jar /usr/bin/

#final checks and notifs! >o<
if ! [ java ]; then
	was_crit_error=1
	echo -e "⛔ java not found in path\n" 
fi

if [ $was_crit_error ]; then
	echo "💔 could not build"
elif [ $was_error ]; then
	echo "⚠️  there was a problem, building anyway"
else
	echo "💖 build finished!"
fi
